## Solution for calculating the inverse of a square matrix
## Solution assumes matrix is a square matrix
## In order to optimize calculation, caching is leveraged for inverse previously calculated
## Two functions are needed to fully implement the caching solution
##   - makeCacheMatrix to set and retrieve initial matrix and inverse 
##   - cacheSolve calculates the inverse for matrix


## makeCacheMatrix takes as argument an initial matrix
## - makeCacheMatrix will create a special "vector"/list for specified matrix 
##    List generated contains as elements functions that set and retrieve initial
##       matrix as well as the inverse

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(xinv) m <<- xinv
  getinverse <- function() m
  list(set = set, get = get, 
       setinverse = setinverse, getinverse = getinverse)
}


## cacheSolve function is accessed for a vector previously generated by makeCacheMatrix
## cacheSolve will calculate the inverse for matrix contained within supplied vector
## The first time accessed, the function will cache the result of the inverse calculation
## Subsequent call will return previously cached inverse and avoid need to calculate again

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data)
  x$setinverse(m)
  m
}

## To begin create square matrix and print
z <- matrix(sample(1:100, 16), 4, 4)
message("Initial matrix")
print(z)

## Now call the constructor for the list needed to contain vector 
##    and associated functions
w <- makeCacheMatrix(z)

## Following demonstrates previous matrix as part of list
message("Matrix as element of list")
print(w$get())

## Now calculate the inverse and print
message("Calculate inverse")
zinv <- cacheSolve(w)

## Following demonstrates calculated inverse as part of list
message("Inverse as element of list")
print(w$getinverse())

## Now repeat the calculation to demonstrate use of cached inverse
message("Demonstrate use of cached inverse matrix")
zinv <- cacheSolve(w)

## Following demonstrates calculated inverse as part of list
message("Demonstrate cached inverse matrix as element of list")
print(w$getinverse())

## Following demonstrates accuracy of the calculated inverse
message("Demonstrate accuracy of inverse matrix")
print(z%*%zinv, digits=0)

## To begin create square matrix and print
z <- matrix(sample(1:100, 25), 5, 5)
message("Repeat for new matrix")
message("Initial matrix")
print(z)

## Now call the constructor for the list needed to contain vector 
##    and associated functions
w <- makeCacheMatrix(z)

## Following demonstrates previous matrix as part of list
message("Matrix as element of list")
print(w$get())

## Now calculate the inverse and print
message("Calculate inverse")
zinv <- cacheSolve(w)

## Following demonstrates calculated inverse as part of list
message("Inverse as element of list")
print(w$getinverse())

## Now repeat the calculation to demonstrate use of cached inverse
message("Demonstrate use of cached inverse matrix")
zinv <- cacheSolve(w)

## Following demonstrates calculated inverse as part of list
message("Demonstrate cached inverse matrix as element of list")
print(w$getinverse())

## Following demonstrates accuracy of the calculated inverse
message("Demonstrate accuracy of inverse matrix")
print(z%*%zinv, digits=0)
