## Solution for calculating the inverse of a square matrix
## Solution does assume matrix is a square matrix
## In order to optimize calculation, caching is leveraged for previous inverse calculated
## Two functions are needed to fully implement the caching solution
##   - makeCacheMatrix to set and retrieve initial matrix and calculated inverse  
##   - cacheSolve to calculate the inverse for matrix




## makeCacheMatrix takes as argument an initial matrix
## - makeCacheMatrix will create a special list for specified matrix 
##    List generated contains as elements functions that set and retrieve initial
##       matrix as well as the inverse


makeCacheMatrix <- function(x = matrix()) {
    xinv <- NULL
    set <- function(y) {
      x <<- y
      xinv <<- NULL
    }
    get <- function() x
    setinverse <- function(y) xinv <<- y
    getinverse <- function() xinv
    list(set = set, get = get, 
         setinverse = setinverse, getinverse = getinverse)
}




## cacheSolve function is accessed for list structure previously generated by makeCacheMatrix
## cacheSolve will calculate the inverse for matrix retrieved by get function within list structure
## The first time accessed, the function will cache the result of the inverse calculation
## Subsequent call will return previously cached inverse and avoid need to calculate again


cacheSolve <- function(x, ...) {
    xinv <- x$getinverse()
    if(!is.null(xinv)) {
      message("getting cached data")
      return(xinv)
    }
    data <- x$get()
    xinv <- solve(data)
    x$setinverse(xinv)
    xinv
}






